"""
Mapping utilities for MDF constants.
Provides type mappings and name conversions for Field enums.
"""

from ._constants import RequestType, Field
from datetime import date, time


# =============================================================================
# REQUEST TYPE MAPPINGS
# =============================================================================

SUB_TYPES = {
    'image': RequestType.IMAGE,
    'stream': RequestType.STREAM,
    'full': RequestType.FULL
}


# =============================================================================
# FIELD NAME MAPPINGS
# =============================================================================

def _create_field_name_mapping():
    """Generate lowercase field names from Field enum."""
    return {field: field.name.lower() for field in Field}


# Auto-generated field name mapping
FIELD_TO_NAME = _create_field_name_mapping()

# Reverse mapping for convenience
NAME_TO_FIELD = {name: field for field, name in FIELD_TO_NAME.items()}


# =============================================================================
# FIELD TYPE MAPPINGS
# =============================================================================
# Based on MDF Fields Reference Document
# Only non-string types need to be specified; defaults to str

FIELD_TYPES = {
    # -------------------------------------------------------------------------
    # Date Fields
    # -------------------------------------------------------------------------
    Field.DATE: date,
    Field.ISSUEDATE: date,
    Field.STRIKEDATE: date,
    Field.RECORDDATE: date,
    Field.PAYMENTDATE: date,
    Field.ANNOUNCEMENTDATE: date,
    Field.ATHDATE: date,
    Field.ATLDATE: date,
    Field.HIGHPRICE1YDATE: date,
    Field.LOWPRICE1YDATE: date,
    Field.HIGHPRICEYTDDATE: date,
    Field.LOWPRICEYTDDATE: date,
    Field.ATHYIELDDATE: date,
    Field.ATLYIELDDATE: date,
    Field.HIGHYIELD1YDATE: date,
    Field.LOWYIELD1YDATE: date,
    Field.HIGHYIELDYTDDATE: date,
    Field.LOWYIELDYTDDATE: date,
    Field.INCEPTIONDATE: date,
    Field.CEOADMISSIONDATE: date,
    Field.CHAIRMANADMISSIONDATE: date,
    Field.TRADEDTHROUGHDATE: date,
    Field.CONVERTFROMDATE: date,
    Field.CONVERTTODATE: date,
    Field.COUPONDATE: date,
    Field.ASIANTAILSTART: date,
    Field.ASIANTAILEND: date,
    Field.SERVERDATE: date,
    Field.D1: date,
    
    # -------------------------------------------------------------------------
    # Time Fields
    # -------------------------------------------------------------------------
    Field.TIME: time,
    Field.TRADETIME: time,
    Field.TRADECANCELTIME: time,
    Field.SERVERTIME: time,
    
    # -------------------------------------------------------------------------
    # Float/Number Fields (prices, rates, amounts, ratios)
    # -------------------------------------------------------------------------
    # Prices
    Field.BIDPRICE: float,
    Field.ASKPRICE: float,
    Field.LASTPRICE: float,
    Field.DAYHIGHPRICE: float,
    Field.DAYLOWPRICE: float,
    Field.TRADEPRICE: float,
    Field.OPENPRICE: float,
    Field.CLOSEPRICE: float,
    Field.CLOSEBIDPRICE: float,
    Field.CLOSEASKPRICE: float,
    Field.CLOSEDAYHIGHPRICE: float,
    Field.CLOSEDAYLOWPRICE: float,
    Field.STRIKEPRICE: float,
    Field.CLOSEPRICE1D: float,
    Field.CLOSEPRICE1W: float,
    Field.CLOSEPRICE1M: float,
    Field.CLOSEPRICE3M: float,
    Field.CLOSEPRICE6M: float,
    Field.CLOSEPRICE9M: float,
    Field.CLOSEPRICE1Y: float,
    Field.CLOSEPRICE2Y: float,
    Field.CLOSEPRICE3Y: float,
    Field.CLOSEPRICE5Y: float,
    Field.CLOSEPRICE10Y: float,
    Field.CLOSEPRICEWTD: float,
    Field.CLOSEPRICEMTD: float,
    Field.CLOSEPRICEQTD: float,
    Field.CLOSEPRICEYTD: float,
    Field.CLOSEPRICEPYTD: float,
    Field.CLOSEPRICELD: float,
    Field.CLOSEPRICE2W: float,
    Field.CLOSEBIDPRICE1D: float,
    Field.CLOSEBIDPRICE1W: float,
    Field.ATH: float,
    Field.ATL: float,
    Field.HIGHPRICE1Y: float,
    Field.LOWPRICE1Y: float,
    Field.HIGHPRICEYTD: float,
    Field.LOWPRICEYTD: float,
    Field.REDEMPTIONPRICE: float,
    Field.SUBSCRIPTIONPRICE: float,
    Field.BARRIERPRICE: float,
    Field.CONVERSIONPRICE: float,
    Field.ISSUEPRICE: float,
    
    # Quantities & Turnover
    Field.QUANTITY: float,
    Field.TURNOVER: float,
    Field.TRADEQUANTITY: float,
    Field.BIDQUANTITY: float,
    Field.ASKQUANTITY: float,
    Field.CLOSEQUANTITY: float,
    Field.CLOSETURNOVER: float,
    Field.INTERNALQUANTITY: float,
    Field.INTERNALTURNOVER: float,
    Field.CLOSEINTERNALQUANTITY: float,
    Field.CLOSEINTERNALTURNOVER: float,
    
    # Yields
    Field.BIDYIELD: float,
    Field.ASKYIELD: float,
    Field.LASTYIELD: float,
    Field.OPENYIELD: float,
    Field.DAYHIGHYIELD: float,
    Field.DAYLOWYIELD: float,
    Field.CLOSEBIDYIELD: float,
    Field.CLOSEASKYIELD: float,
    Field.CLOSEYIELD: float,
    Field.CLOSEDAYHIGHYIELD: float,
    Field.CLOSEDAYLOWYIELD: float,
    Field.CLOSEYIELD1D: float,
    Field.CLOSEYIELD1W: float,
    Field.CLOSEYIELD2W: float,
    Field.CLOSEYIELD1M: float,
    Field.CLOSEYIELD3M: float,
    Field.CLOSEYIELD6M: float,
    Field.CLOSEYIELD9M: float,
    Field.CLOSEYIELD1Y: float,
    Field.CLOSEYIELD2Y: float,
    Field.CLOSEYIELD3Y: float,
    Field.CLOSEYIELD5Y: float,
    Field.CLOSEYIELD10Y: float,
    Field.CLOSEYIELDWTD: float,
    Field.CLOSEYIELDMTD: float,
    Field.CLOSEYIELDQTD: float,
    Field.CLOSEYIELDYTD: float,
    Field.CLOSEYIELDPYTD: float,
    Field.CLOSEYIELDLD: float,
    Field.CLOSEBIDYIELD1D: float,
    Field.CLOSEBIDYIELD1W: float,
    Field.ATHYIELD: float,
    Field.ATLYIELD: float,
    Field.HIGHYIELD1Y: float,
    Field.LOWYIELD1Y: float,
    Field.HIGHYIELDYTD: float,
    Field.LOWYIELDYTD: float,
    Field.TRADEYIELD: float,
    
    # Fund/NAV
    Field.NAV: float,
    Field.CLOSENAV: float,
    Field.TIS: float,
    Field.CLOSETIS: float,
    
    # Dividends
    Field.DIVIDEND: float,
    
    # Shares & Adjustments
    Field.ADJUSTMENTFACTOR: float,
    Field.NUMBEROFSHARES: float,
    Field.NUMBEROFSHARESDELTA: float,
    Field.NEWSHARES: float,
    Field.OLDSHARES: float,
    Field.NOMINALVALUE: float,
    
    # Market Metrics
    Field.VWAP: float,
    Field.CLOSEVWAP: float,
    Field.MCAP: float,
    Field.CONTRACTSIZE: float,
    Field.BASERATIO: float,
    Field.OPENINTEREST: float,
    
    # Financial Statement Items
    Field.SALES: float,
    Field.EBIT: float,
    Field.PRETAXPROFIT: float,
    Field.NETPROFIT: float,
    Field.EPS: float,
    Field.DILUTEDEPS: float,
    Field.EBITDA: float,
    Field.EBITA: float,
    Field.NETFININCOME: float,
    Field.GROSSPROFIT: float,
    Field.NETSALES: float,
    Field.ADJUSTEDEBITA: float,
    
    # Balance Sheet Items
    Field.INTANGIBLEASSET: float,
    Field.GOODWILL: float,
    Field.FIXEDASSET: float,
    Field.FINANCIALASSET: float,
    Field.NONCURRENTASSET: float,
    Field.INVENTORY: float,
    Field.OTHERCURRENTASSET: float,
    Field.ACCOUNTSRECEIVABLE: float,
    Field.OTHERRECEIVABLES: float,
    Field.SHORTTERMINV: float,
    Field.CCE: float,
    Field.CURRENTASSETS: float,
    Field.TOTALASSETS: float,
    Field.SHEQUITY: float,
    Field.MINORITYINTEREST: float,
    Field.PROVISIONS: float,
    Field.LTLIABILITIES: float,
    Field.CURLIABILITIES: float,
    Field.TOTSHEQLIABILITIES: float,
    Field.NIBL: float,
    Field.IBL: float,
    Field.ACCOUNTSPAYABLE: float,
    
    # Cash Flow Items
    Field.CASHFLOWBWC: float,
    Field.CASHFLOWAWC: float,
    Field.CASHFLOWIA: float,
    Field.CASHFLOWFA: float,
    Field.CASHFLOWTOTAL: float,
    Field.OPERATINGCASHFLOW: float,
    
    # Ratios & Percentages
    Field.VOTINGPOWERPRC: float,
    Field.CAPITALPRC: float,
    Field.EQUITYRATIO: float,
    
    # Fund-Specific
    Field.FUNDYEARLYMGMTFEE: float,
    Field.FUNDPPMFEE: float,
    Field.FUNDLEVERAGE: float,
    Field.STANDARDDEVIATION3Y: float,
    Field.ANNUALIZEDRETURN1Y: float,
    Field.ANNUALIZEDRETURN2Y: float,
    Field.ANNUALIZEDRETURN3Y: float,
    Field.ANNUALIZEDRETURN4Y: float,
    Field.ANNUALIZEDRETURN5Y: float,
    Field.ANNUALIZEDRETURN10Y: float,
    Field.SHARPERATIO3Y: float,
    Field.MORNINGSTARRATING: float,
    Field.SALESFEE: float,
    Field.PURCHASEFEE: float,
    Field.MINSTARTAMOUNT: float,
    Field.MINSUBSCRIPTIONAMOUNT: float,
    Field.PERFORMANCEFEE: float,
    Field.MINADDITIONALAMOUNT: float,
    Field.TOTALFEE: float,
    
    # Options/Derivatives
    Field.DURATION: float,
    Field.CAP: float,
    Field.FINANCIALINCOME: float,
    Field.FINANCIALCOST: float,
    Field.FINANCINGLEVEL: float,
    Field.PARTICIPATIONRATE: float,
    Field.MAXLEVEL: float,
    
    # Statistics
    Field.AVERAGE: float,
    Field.MIN: float,
    Field.MAX: float,
    
    # Income Statement
    Field.INTERESTINCOME: float,
    Field.OTHERFINANCIALINCOME: float,
    Field.INTERESTEXPENSE: float,
    Field.OTHERFINANCIALEXPENSE: float,
    Field.MINORITYINTERESTRES: float,
    
    # Placeholders (numeric)
    Field.N1: float,
    Field.N2: float,
    Field.N3: float,
    Field.N4: float,
    Field.N5: float,
    
    # -------------------------------------------------------------------------
    # Integer Fields (counts, codes, flags, enum values, insref)
    # -------------------------------------------------------------------------
    # Order Book
    Field.ORDERLEVEL: int,
    Field.NUMBIDORDERS: int,
    Field.NUMASKORDERS: int,
    Field.NUMTRADES: int,
    Field.CLOSENUMTRADES: int,
    
    # Request/Status
    Field.REQUESTSTATUS: int,
    Field.REQUESTTYPE: int,
    Field.REQUESTCLASS: int,
    
    # Instrument References (insref type)
    Field.COMPANY: int,
    Field.FUNDCOMPANY: int,
    Field.MARKETPLACE: int,
    Field.PRIMARYMARKETPLACE: int,
    Field.TICKTABLE: int,
    
    # Instrument Classification
    Field.INSTRUMENTTYPE: int,
    Field.INSTRUMENTSUBTYPE: int,
    Field.DERIVATIVEINDICATOR: int,
    Field.EXERCISETYPE: int,
    Field.INSTRUMENTCLASS: int,
    
    # Trade & Market State
    Field.TRADECODE: int,
    Field.EXECUTEDSIDE: int,
    Field.SPECIALCONDITION: int,
    Field.TRADESTATE: int,
    
    # Corporate Actions
    Field.CATYPE: int,
    Field.CASUBTYPE: int,
    
    # News
    Field.NEWSCODINGTYPE: int,
    Field.NEWSCODINGSUBJECT: int,
    Field.NEWSISLASTBLOCK: int,
    Field.NEWSBLOCKNUMBER: int,
    Field.NEWSRANK: int,
    
    # Fund Codes
    Field.FUNDPPMCODE: int,
    Field.FIINSTITUTENUMBER: int,
    
    # Counts & Indices
    Field.COUNT: int,
    Field.NUMEMPLOYEES: int,
    Field.TID: int,
    
    # Product Classification
    Field.DIVIDENDTYPE: int,
    Field.DIVIDENDFREQUENCY: int,
    Field.FUNDRISK: int,
    Field.EUSIPA: int,
    Field.PRICETYPE: int,
    Field.SETTLEMENTTYPE: int,
    
    # Order Imbalance
    Field.CROSSTYPE: int,
    Field.IMBALANCE: int,
    Field.IMBALANCEDIRECTION: int,
    
    # Other
    Field.VOTINGPOWER: int,
    Field.CONTRACTVALUE: int,
    Field.DELETERECORD: int,
    
    # Placeholders (integer)
    Field.I1: int,
    Field.I2: int,
    Field.I3: int,
    Field.I4: int,
    Field.I5: int,
    
    # -------------------------------------------------------------------------
    # List Fields
    # -------------------------------------------------------------------------
    Field.INSREFLIST: list,
    Field.LIST: list,
    Field.NEWSCODINGCOMPANY: list,
    Field.SECTOR: list,
    
    # =========================================================================
    # Additional fields typed from the MDF Fields Reference (22 September 2026)
    # =========================================================================
    # -------------------------------------------------------------------------
    # Date Fields
    # -------------------------------------------------------------------------
    Field.BIRTHYEARCEO: date,
    Field.BIRTHYEARCHAIRMAN: date,
    Field.D2: date,
    Field.D3: date,
    Field.TRADEAGREEMENTDATE: date,
    Field.PRIIP04083: date,
    Field.MIFID08090: date,
    Field.MIFID08100: date,
    Field.MIFID01000: date,
    Field.MIFID07160: date,
    Field.CLOSEPRICE1DDATE: date,
    Field.CLOSEPRICEDATE: date,
    Field.PRIIP02035: date,
    Field.PRIIP02065: date,
    Field.PRIIP02095: date,
    Field.PRIIP02125: date,
    Field.PRIIP06005: date,
    Field.PRIIP07005: date,
    
    # -------------------------------------------------------------------------
    # Time Fields
    # -------------------------------------------------------------------------
    Field.MARKETOPEN: time,
    Field.MARKETCLOSE: time,
    Field.MARKETEARLYCLOSE: time,
    Field.TRADEAGREEMENTTIME: time,
    
    # -------------------------------------------------------------------------
    # Float/Number Fields
    # -------------------------------------------------------------------------
    Field.BOARDLOT: float,
    Field.UNCHANGEDPAID: float,
    Field.PLUSPAID: float,
    Field.MINUSPAID: float,
    Field.NETINTERESTINCOME: float,
    Field.DY: float,
    Field.PER_TTM: float,
    Field.PSR_TTM: float,
    Field.GENIUMID: float,
    Field.COUPONRATE: float,
    Field.OFFBOOKQUANTITY: float,
    Field.OFFBOOKTURNOVER: float,
    Field.DARKQUANTITY: float,
    Field.DARKTURNOVER: float,
    Field.CLOSEOFFBOOKQUANTITY: float,
    Field.CLOSEOFFBOOKTURNOVER: float,
    Field.CLOSEDARKQUANTITY: float,
    Field.CLOSEDARKTURNOVER: float,
    Field.SETTLEMENTPRICE: float,
    Field.SEQUENCE: float,
    Field.OUTSTANDINGAMOUNT: float,
    Field.INTERESTRATE: float,
    Field.NUMBEROFPREFSHARES: float,
    Field.ONGOINGCHARGE: float,
    Field.CLOSETRADEPRICE: float,
    Field.NETDIVIDEND: float,
    Field.LATESTYEARENDREPORT: float,
    Field.NORMANAMOUNT: float,
    Field.CSR: float,
    Field.CIK: float,
    Field.PRIIP00080: float,
    Field.PRIIP01020: float,
    Field.PRIIP01040: float,
    Field.PRIIP01050: float,
    Field.PRIIP01070: float,
    Field.PRIIP01090: float,
    Field.PRIIP01100: float,
    Field.PRIIP01110: float,
    Field.PRIIP01120: float,
    Field.PRIIP02010: float,
    Field.PRIIP02020: float,
    Field.PRIIP02030: float,
    Field.PRIIP02040: float,
    Field.PRIIP02050: float,
    Field.PRIIP02060: float,
    Field.PRIIP02070: float,
    Field.PRIIP02080: float,
    Field.PRIIP02090: float,
    Field.PRIIP02100: float,
    Field.PRIIP02110: float,
    Field.PRIIP02120: float,
    Field.PRIIP02130: float,
    Field.PRIIP02140: float,
    Field.PRIIP02150: float,
    Field.PRIIP02160: float,
    Field.PRIIP02170: float,
    Field.PRIIP02180: float,
    Field.PRIIP03010: float,
    Field.PRIIP03015: float,
    Field.PRIIP03020: float,
    Field.PRIIP03030: float,
    Field.PRIIP03040: float,
    Field.PRIIP03060: float,
    Field.PRIIP03070: float,
    Field.PRIIP03080: float,
    Field.PRIIP03095: float,
    Field.PRIIP03105: float,
    Field.PRIIP04081: float,
    Field.PRIIP04085: float,
    Field.PRIIP05030: float,
    Field.PRIIP05040: float,
    Field.PRIIP05050: float,
    Field.PRIIP05060: float,
    Field.PRIIP05070: float,
    Field.PRIIP05080: float,
    Field.PRIIP06010: float,
    Field.PRIIP06020: float,
    Field.PRIIP06030: float,
    Field.PRIIP06050: float,
    Field.PRIIP06080: float,
    Field.PRIIP07010: float,
    Field.PRIIP07020: float,
    Field.PRIIP07030: float,
    Field.PRIIP07040: float,
    Field.PRIIP07050: float,
    Field.PRIIP07060: float,
    Field.PRIIP07070: float,
    Field.PRIIP07080: float,
    Field.PRIIP07090: float,
    Field.PRIIP07100: float,
    Field.PRIIP07110: float,
    Field.PRIIP07120: float,
    Field.MIFID03030: float,
    Field.MIFID04010: float,
    Field.MIFID04020: float,
    Field.MIFID04040: float,
    Field.MIFID05080N: float,
    Field.MIFID07020: float,
    Field.MIFID07030: float,
    Field.MIFID07040: float,
    Field.MIFID07050: float,
    Field.MIFID07060: float,
    Field.MIFID07070: float,
    Field.MIFID07080: float,
    Field.MIFID07090: float,
    Field.MIFID07100: float,
    Field.MIFID07110: float,
    Field.MIFID07120: float,
    Field.MIFID07130: float,
    Field.MIFID07140: float,
    Field.MIFID08010: float,
    Field.MIFID08020: float,
    Field.MIFID08030: float,
    Field.MIFID08040: float,
    Field.MIFID08050: float,
    Field.MIFID08060: float,
    Field.MIFID08070: float,
    Field.MIFID08080: float,
    Field.CVR: float,
    Field.KENNITALA: float,
    Field.ORGNUMNO: float,
    Field.NEWSCODINGIMPACT: float,
    Field.ACTIVESHARE: float,
    Field.TRACKINGERROR: float,
    Field.HIGHPRICE3Y: float,
    Field.LOWPRICE3Y: float,
    Field.HIGHPRICE5Y: float,
    Field.LOWPRICE5Y: float,
    Field.HIGHPRICE10Y: float,
    Field.LOWPRICE10Y: float,
    Field.DPS: float,
    Field.CFPS: float,
    Field.CFPS_TTM: float,
    Field.CFPS_LAST: float,
    Field.EPS_TTM: float,
    Field.EPS_LAST: float,
    Field.SPS: float,
    Field.SPS_TTM: float,
    Field.SPS_LAST: float,
    Field.BVPS: float,
    Field.BVPS_LAST: float,
    Field.ROE: float,
    Field.ROE_TTM: float,
    Field.ROE_LAST: float,
    Field.ROA: float,
    Field.ROA_TTM: float,
    Field.ROA_LAST: float,
    Field.GM: float,
    Field.GM_TTM: float,
    Field.GM_LAST: float,
    Field.OM: float,
    Field.OM_TTM: float,
    Field.OM_LAST: float,
    Field.PM: float,
    Field.PM_TTM: float,
    Field.PM_LAST: float,
    Field.MIFID00095: float,
    Field.MIFID07025: float,
    Field.MIFID07105: float,
    Field.MIFID07150: float,
    Field.MIFID07155: float,
    Field.MIFID08015: float,
    Field.MIFID08025: float,
    Field.MIFID08045: float,
    Field.MIFID08110: float,
    Field.MIFID08120: float,
    Field.COUPONFREQUENCY: float,
    Field.ORDERID: float,
    Field.ORDERPRIORITY: float,
    Field.IV: float,
    Field.DELTA: float,
    Field.GAMMA: float,
    Field.RHO: float,
    Field.THETA: float,
    Field.VEGA: float,
    Field.ORDERPRICE: float,
    Field.ORDERQUANTITY: float,
    Field.IVBID: float,
    Field.IVASK: float,
    Field.N6: float,
    Field.N7: float,
    Field.N8: float,
    Field.N9: float,
    Field.N10: float,
    Field.I6: float,
    Field.I7: float,
    Field.I8: float,
    Field.I9: float,
    Field.I10: float,
    Field.SWINGFACTOR: float,
    Field.INCOMEPROPMAN: float,
    Field.PRIIP02210: float,
    Field.PRIIP02220: float,
    Field.CLOSEPRICE4Y: float,
    Field.CLOSEPRICE6Y: float,
    Field.CLOSEPRICE7Y: float,
    Field.CLOSEPRICE8Y: float,
    Field.CLOSEPRICE9Y: float,
    Field.CLOSEYIELD4Y: float,
    Field.CLOSEYIELD6Y: float,
    Field.CLOSEYIELD7Y: float,
    Field.CLOSEYIELD8Y: float,
    Field.CLOSEYIELD9Y: float,
    Field.SWINGFACTORSUB: float,
    Field.AVGTURNOVER1W: float,
    Field.AVGTURNOVER1M: float,
    Field.AVGTURNOVER3M: float,
    Field.AVGTURNOVER1Y: float,
    Field.AVGTURNOVERYTD: float,
    Field.SMA20: float,
    Field.SMA50: float,
    Field.SMA200: float,
    Field.RSI14: float,
    Field.MACD: float,
    Field.PER_LAST: float,
    Field.PSR_LAST: float,
    Field.PBR: float,
    Field.PCF_TTM: float,
    Field.PCF_LAST: float,
    Field.DER: float,
    Field.DER_LAST: float,
    Field.ND_EBITDA: float,
    Field.ND_EBITDA_TTM: float,
    Field.ND_EBITDA_LAST: float,
    Field.DPR: float,
    Field.ROIC: float,
    Field.ROIC_TTM: float,
    Field.ROIC_LAST: float,
    Field.PEG: float,
    Field.PEG_TTM: float,
    Field.PEG_LAST: float,
    Field.FCFF: float,
    Field.CAPEX: float,
    Field.ROUAMORTIZATION: float,
    
    # -------------------------------------------------------------------------
    # Integer Fields (uint, bitfield, bool, insref, enum)
    # -------------------------------------------------------------------------
    Field.UCITS: int,
    Field.FUNDBENCHMARKINSREF: int,
    Field.CITYPE: int,
    Field.CISUBTYPE: int,
    Field.PRICINGFREQUENCY: int,
    Field.MARKETOPENDAYS: int,
    Field.CLOSEPRICETYPE: int,
    Field.QUOTINGTYPE: int,
    Field.VOLUMEDIMENSION: int,
    Field.NEWSCODINGREGULATORY: int,
    Field.PRIIP00040: int,
    Field.PRIIP01010: int,
    Field.SUBMARKET: int,
    Field.MIFID00020: int,
    Field.MMO: int,
    Field.ORDERSIDE: int,
    Field.DAYCOUNTCONVENTION: int,
    Field.EXPIRATIONTYPE: int,
    Field.INSREF1: int,
    Field.INSREF2: int,
    Field.INSREF3: int,
    Field.INSREF4: int,
    Field.INSREF5: int,
    Field.SWINGMETHOD: int,
    Field.LASTMOD: int,
    Field.EVENTSTATUS: int,
    Field.TRADESTATEACTIONS: int,
    Field.PRIMARYSHARE: int,
    
    # -------------------------------------------------------------------------
    # List Fields
    # -------------------------------------------------------------------------
    Field.SECTORMEMBERS: list,
}
